# Generated by Django 6.0.6 on 2026-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=128)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'event_id'], name='tenant_proc_provide_9126c2_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_provider_event')],
            },
        ),
    ]
