# Generated by Django 6.0.6 on 2026-07-28 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_company_name'),
        ('tenant', '0002_processedwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['tenant', 'provider', 'is_default'], name='tenant_paym_tenant__10eea4_idx'),
        ),
    ]
