# Generated by Django 6.0.6 on 2026-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_alter_rentpayment_provider_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed'), ('OVERDUE', 'Overdue'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
