# Generated by Django 6.0.6 on 2026-08-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_alter_rentpayment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentpayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='rentpayment',
            name='tenant_rent_tenant__4120b4_idx',
        ),
    ]
