# Generated by Django 6.0.6 on 2026-08-07 06:01

import apps.tenant.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_organisationuser_status'),
        ('property', '0014_property_company_name'),
        ('tenant', '0006_cardpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('issue', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('CARPENTRY_SECURITY', 'Carpentry_Security'), ('OTHER', 'Other')], default='plumbing', max_length=32)),
                ('current_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.tenant.utils.receipt_upload_path)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='organisation.organisation')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='property.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='property.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['organisation', 'tenant'], name='tenant_main_organis_68dc7a_idx'), models.Index(fields=['current_status'], name='tenant_main_current_53481c_idx')],
            },
        ),
    ]
