# Generated by Django 6.0.6 on 2026-08-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('CARPENTRY_SECURITY', 'Carpentry_Security'), ('OTHER', 'Other')], default='PLUMBING', max_length=32),
        ),
    ]
