# Generated by Django 6.0.6 on 2026-08-10 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_organisationuser_status'),
        ('property', '0014_property_company_name'),
        ('tenant', '0008_alter_maintenancerequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_maintenance_requests', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_maintenance_requests', to='property.property'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_maintenance_requests', to='property.tenant'),
        ),
    ]
