# Generated by Django 6.0.6 on 2026-08-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('tenant', '0009_alter_maintenancerequest_organisation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerequest',
            old_name='description',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='document',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='maintenance_requests', to='common.documentfile'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
