# Generated by Django 6.0.6 on 2026-08-14 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('property', '0019_remove_mortgageadvisermortgagepermission_unique_mortgage_adviser_mortgage_permission_and_more'),
        ('tenant', '0010_rename_description_maintenancerequest_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('message', models.TextField(verbose_name='Message')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('documents', models.ManyToManyField(blank=True, related_name='maintenance_request_comments', to='common.documentfile', verbose_name='Attachments')),
                ('maintenance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request_comments', to='tenant.maintenancerequest', verbose_name='Maintenance Request')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tenant.maintenancerequestcomment', verbose_name='Parent Comment')),
                ('staff_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request_comments', to=settings.AUTH_USER_MODEL, verbose_name='Commented By (Staff)')),
                ('tenant_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_request_comments', to='property.tenant', verbose_name='Commented By (Tenant)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Maintenance Request Comment',
                'verbose_name_plural': 'Maintenance Request Comments',
                'ordering': ['-created_at', '-updated_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('staff_author__isnull', False), ('tenant_author__isnull', True)), models.Q(('staff_author__isnull', True), ('tenant_author__isnull', False)), _connector='OR'), name='maintenance_comment_single_author')],
            },
        ),
    ]
