# Generated by Django 6.0.6 on 2026-08-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_maintenancerequestcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(blank=True, choices=[('PLUMBING', 'Plumbing'), ('CARPENTRY_SECURITY', 'Carpentry_Security'), ('OTHER', 'Other')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='current_status',
            field=models.CharField(blank=True, choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=20, null=True),
        ),
    ]
