# Generated by Django 6.0.6 on 2026-08-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_alter_maintenancerequest_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('CARPENTRY_SECURITY', 'Carpentry_Security'), ('OTHER', 'Other')], default='PLUMBING', max_length=32),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='current_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20),
        ),
    ]
