# Generated by Django 6.0.6 on 2026-09-21 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_organisationsubscription_pending_plan_and_more'),
        ('property', '0025_remove_complianceandcertification_shared_with'),
        ('tenant', '0016_remove_processedwebhookevent_tenant_proc_provide_9126c2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_card_payments', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='cardpayment',
            index=models.Index(fields=['organisation', 'due_date'], name='tenant_card_organis_87461d_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='unique_default_payment_method_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organisation',), name='unique_default_payment_method_per_organisation'),
        ),
    ]
