# Generated by Django 6.0.6 on 2026-09-21 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_organisationsubscription_pending_plan_and_more'),
        ('tenant', '0017_cardpayment_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_card_payments', to='organisation.organisation'),
        ),
    ]
