# Generated by Django 6.0.6 on 2026-09-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0018_alter_cardpayment_organisation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rentpayment',
            name='tenant_rent_tenant__1f99e6_idx',
        ),
        migrations.DeleteModel(
            name='RentPayment',
        ),
    ]
