# Generated by Django 6.0.6 on 2026-09-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_remove_rentpayment_tenant_rent_tenant__1f99e6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
