# Generated by Django 6.0.6 on 2026-09-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0020_cardpayment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
