# Generated by Django 6.0.6 on 2026-07-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'Urgent'), ('MEDIUM', 'Medium'), ('NORMAL', 'Normal'), ('WHEN_POSSIBLE', 'When Possible')], default='WHEN_POSSIBLE', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status'),
        ),
    ]
