# Generated by Django 6.0.6 on 2026-07-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supportticket', '0002_supportticket_priority_supportticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
