# Generated by Django 6.0.6 on 2026-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('LANDLORD', 'Landlord'), ('MORTGAGE_ADVISER', 'Mortgage Adviser'), ('ACCOUNTANT', 'Accountant'), ('LETTING_AGENT', 'Letting Agent'), ('ADMIN', 'Admin')], max_length=20, null=True),
        ),
    ]
