# Generated by Django 6.0.6 on 2026-07-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('MISS', 'Miss.'), ('MADAM', 'Madam.'), ('MAIDEN', 'Maiden.'), ('PROFESSOR', 'Professor.'), ('DOCTOR', 'Doctor.')], max_length=64, null=True),
        ),
    ]
