# Generated by Django 6.0.6 on 2026-07-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ni_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='utr_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
