# Generated by Django 6.0.6 on 2026-08-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_current_address_user_ni_number_user_utr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='role',
            field=models.CharField(choices=[('LANDLORD', 'Landlord'), ('ADMIN', 'Admin'), ('MORTGAGE_ADVISER', 'Mortgage Adviser'), ('LETTING_AGENT', 'Letting Agent')], default='LANDLORD', max_length=64),
        ),
    ]
