# Generated by Django 6.0.6 on 2026-07-02 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_inviteuser'),
        ('organisation', '0002_remove_organisation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteuser',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organisation.organisation', verbose_name='Organisation'),
            preserve_default=False,
        ),
    ]
