# Generated by Django 6.0.6 on 2026-08-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_permission'),
        ('organisation', '0004_alter_organisationuser_role'),
        ('property', '0022_remove_mortgagepermission_unique_user_mortgage_permission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={},
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('property__isnull', False), ('mortgage__isnull', False), _connector='XOR'), name='permission_property_or_mortgage'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('user', 'property'), name='unique_user_property_permission'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('mortgage__isnull', False)), fields=('user', 'mortgage'), name='unique_user_mortgage_permission'),
        ),
    ]
