# Generated by Django 6.0.6 on 2026-08-17 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_permission_options_and_more'),
        ('organisation', '0004_alter_organisationuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_permissions', to='organisation.organisation'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
