# Generated by Django 6.0.6 on 2026-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_permission_user'),
        ('organisation', '0004_alter_organisationuser_role'),
        ('property', '0022_remove_mortgagepermission_unique_user_mortgage_permission_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_user_property_permission',
        ),
        migrations.RemoveConstraint(
            model_name='permission',
            name='unique_user_mortgage_permission',
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('property__isnull', False)), fields=('organisation', 'user', 'property'), name='unique_org_user_property_permission'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(condition=models.Q(('mortgage__isnull', False)), fields=('organisation', 'user', 'mortgage'), name='unique_org_user_mortgage_permission'),
        ),
    ]
