# Generated by Django 6.0.6 on 2026-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_permission_unique_user_property_permission_and_more'),
        ('organisation', '0004_alter_organisationuser_role'),
        ('property', '0022_remove_mortgagepermission_unique_user_mortgage_permission_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.CheckConstraint(condition=models.Q(('can_edit', False), ('can_view', True), _connector='OR'), name='permission_edit_requires_view'),
        ),
    ]
