# Generated by Django 6.0.6 on 2026-07-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceandcertification',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
