# Generated by Django 6.0.6 on 2026-06-19 05:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAndCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('epc', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_type', models.CharField(blank=True, choices=[('GAS_SAFETY_CERTIFICATE', 'Gas Safety Certificate'), ('EPC_CERTIFICATE', 'EPC Certificate'), ('ELECTRICAL_SAFETY_CERTIFICATE', 'Electrical Safety Certificate'), ('FIRE_RISK_ASSESSMENT', 'Fire Risk Assessment'), ('HMO_LICENCE', 'HMO Licence'), ('PAT_TESTING', 'PAT Testing'), ('LEGIONELLA_ASSESSMENT', 'Legionella Assessment'), ('INSURANCE_DOCUMENT', 'Insurance Document')], max_length=50, null=True)),
                ('gas_safety_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('electrical_safety_certificate', models.CharField(blank=True, max_length=255, null=True)),
                ('fire_risk_assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('hmo_licence', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_documents', models.CharField(blank=True, max_length=255, null=True)),
                ('pat_testing', models.CharField(blank=True, max_length=255, null=True)),
                ('legionella_assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='compliance_certificates/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_certificates', to='property.property')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Compliance and Certification',
                'verbose_name_plural': 'Compliance and Certifications',
            },
        ),
    ]
