# Generated by Django 6.0.6 on 2026-06-24 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('property', '0002_property_rent_per_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='INCOME', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('RENTAL_INCOME', 'Rental Income'), ('MORTGAGE_PAYMENT', 'Mortgage Payment'), ('REPAIRS', 'Repairs'), ('INSURANCE', 'Insurance'), ('SERVICE_CHARGES', 'Service Charges'), ('UTILITIES', 'Utilities'), ('MANAGEMENT_FEES', 'Management Fees'), ('TAX', 'Tax'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_property', to='property.property')),
                ('receipt', models.ManyToManyField(blank=True, related_name='finance_documents', to='common.documentfile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
