# Generated by Django 6.0.6 on 2026-07-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_complianceandcertification_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
