# Generated by Django 6.0.6 on 2026-06-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_remove_organisation_email_and_more'),
        ('property', '0003_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='finance_organisation', to='organisation.organisation'),
            preserve_default=False,
        ),
    ]
