# Generated by Django 6.0.6 on 2026-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_tenant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.'), ('DR', 'Dr.'), ('MISS', 'Miss.'), ('MADAM', 'Madam.'), ('MAIDEN', 'Maiden.'), ('PROFESSOR', 'Professor.'), ('DOCTOR', 'Doctor.')], max_length=20, null=True),
        ),
    ]
