# Generated by Django 6.0.6 on 2026-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_complianceandcertification_electrical_safety_certificate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='notes',
            new_name='broker_notes',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='variable_type',
        ),
        migrations.AddField(
            model_name='mortgage',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='mortgage_product_type',
            field=models.CharField(blank=True, choices=[('FIXED_RATE', 'Fixed Rate'), ('VARIABLE_RATE', 'Variable Rate'), ('TRACKER', 'Tracker'), ('OFFSET', 'Offset')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='product_type',
            field=models.CharField(blank=True, choices=[('FIXED_RATE', 'Fixed Rate'), ('VARIABLE_RATE', 'Variable Rate'), ('TRACKER', 'Tracker'), ('OFFSET', 'Offset')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('OCCUPIED', 'Occupied'), ('VACANT', 'Vacant'), ('UNDER_MAINTENANCE', 'Under Maintenance')], max_length=50, null=True),
        ),
    ]
