# Generated by Django 6.0.6 on 2026-07-20 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_organisationuser_status'),
        ('property', '0006_alter_tenant_options_remove_tenant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['organisation', 'email'], name='property_te_organis_38f6a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(fields=('organisation', 'email'), name='unique_tenant_email_per_org'),
        ),
    ]
