# Generated by Django 6.0.6 on 2026-07-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_tenant_property_te_organis_38f6a5_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='end_date',
            new_name='epc_certificate_expiry_date',
        ),
        migrations.RenameField(
            model_name='mortgage',
            old_name='start_date',
            new_name='interest_rate_expiry_date',
        ),
        migrations.RenameField(
            model_name='mortgage',
            old_name='broker_notes',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='mortgage',
            old_name='term',
            new_name='remaining_mortgage',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='loan_amount',
        ),
        migrations.RemoveField(
            model_name='mortgage',
            name='product_type',
        ),
        migrations.AddField(
            model_name='mortgage',
            name='epc_rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mortgage',
            name='interest_rate_type',
            field=models.CharField(blank=True, choices=[('FIXED_RATE', 'Fixed Rate'), ('VARIABLE_RATE', 'Variable Rate'), ('TRACKER', 'Tracker'), ('OFFSET', 'Offset')], max_length=50, null=True),
        ),
    ]
