# Generated by Django 6.0.6 on 2026-07-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_drop_orphan_mortgage_documents_table'),
        ('property', '0006_mortgage_mortgage_documents_tenant_image'),
        ('property', '0007_alter_tenant_property'),
    ]

    operations = [
    ]
