# Generated by Django 6.0.6 on 2026-07-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_rename_end_date_mortgage_epc_certificate_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='rent_per_month',
            new_name='annual_ground_rent',
        ),
        migrations.AddField(
            model_name='property',
            name='council_tax_band',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='local_authority',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_rental_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly_service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_owner',
            field=models.CharField(blank=True, choices=[('OWN', 'Own'), ('COMPANY', 'Company')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_tenure',
            field=models.CharField(blank=True, choices=[('FREEHOLD', 'Freehold'), ('LEASEHOLD', 'Leasehold')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='remaining_lease_term',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'House'), ('FLAT', 'Flat'), ('MAISONETTE', 'Maisonette'), ('BUNGALOW', 'Bungalow'), ('RESIDENTIAL', 'Residential'), ('HMO', 'HMO'), ('COMMERCIAL', 'Commercial'), ('HOLIDAY_LET', 'Holiday Let')], default='RESIDENTIAL', max_length=20),
        ),
    ]
