# Generated by Django 6.0.6 on 2026-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_propertyownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_owner',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('COMPANY', 'Company')], default='OWNER', max_length=64),
        ),
    ]
