# Generated by Django 6.0.6 on 2026-07-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_property_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyownership',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholder', to='property.property'),
        ),
        migrations.AlterField(
            model_name='propertyownership',
            name='share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
