# Generated by Django 6.0.6 on 2026-07-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_propertyownership_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyownership',
            name='shareholder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
