# Generated by Django 6.0.6 on 2026-07-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_propertyownership_shareholder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
