# Generated by Django 6.0.6 on 2026-08-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_property_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='is_visible_mortgage_adviser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='is_visible_mortgage_adviser',
            field=models.BooleanField(default=False),
        ),
    ]
