# Generated by Django 6.0.6 on 2026-08-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_mortgageadvisermortgagepermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mortgage',
            name='is_visible_mortgage_adviser',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_visible_mortgage_adviser',
        ),
    ]
