# Generated by Django 6.0.6 on 2026-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_remove_mortgage_is_visible_mortgage_adviser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
    ]
