# Generated by Django 6.0.6 on 2026-08-13 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_alter_organisationuser_role'),
        ('property', '0018_tenant_is_password_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mortgageadvisermortgagepermission',
            name='unique_mortgage_adviser_mortgage_permission',
        ),
        migrations.RemoveConstraint(
            model_name='mortgageadviserpropertypermission',
            name='unique_mortgage_adviser_property_permission',
        ),
        migrations.AddField(
            model_name='mortgageadvisermortgagepermission',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_mortgage_permissions', to='organisation.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mortgageadviserpropertypermission',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_property_permissions', to='organisation.organisation'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='mortgageadvisermortgagepermission',
            constraint=models.UniqueConstraint(fields=('mortgage_adviser', 'mortgage', 'organisation'), name='unique_mortgage_adviser_mortgage_permission'),
        ),
        migrations.AddConstraint(
            model_name='mortgageadviserpropertypermission',
            constraint=models.UniqueConstraint(fields=('mortgage_adviser', 'property', 'organisation'), name='unique_mortgage_adviser_property_permission'),
        ),
    ]
