# Generated by Django 6.0.6 on 2026-08-14 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0004_alter_organisationuser_role'),
        ('property', '0020_propertypermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mortgageadvisermortgagepermission',
            name='unique_mortgage_adviser_mortgage_permission',
        ),
        migrations.AddField(
            model_name='mortgagepermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='mortgagepermission',
            name='mortgage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortgage_permissions', to='property.mortgage'),
        ),
        migrations.AddField(
            model_name='mortgagepermission',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_mortgage_permissions', to='organisation.organisation'),
        ),
        migrations.AddField(
            model_name='mortgagepermission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='mortgagepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mortgage_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mortgageadvisermortgagepermission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='mortgageadvisermortgagepermission',
            name='mortgage',
        ),
        migrations.RemoveField(
            model_name='mortgageadvisermortgagepermission',
            name='mortgage_adviser',
        ),
        migrations.RemoveField(
            model_name='mortgageadvisermortgagepermission',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='mortgageadvisermortgagepermission',
            name='updated_by',
        ),
        migrations.AddConstraint(
            model_name='mortgagepermission',
            constraint=models.UniqueConstraint(fields=('user', 'mortgage', 'organisation'), name='unique_user_mortgage_permission'),
        ),
        migrations.DeleteModel(
            name='MortgageAdviserMortgagePermission',
        ),
    ]
