# Generated by Django 6.0.6 on 2026-08-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_mortgagepermission_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mortgagepermission',
            name='unique_user_mortgage_permission',
        ),
        migrations.RemoveConstraint(
            model_name='propertypermission',
            name='unique_user_property_permission',
        ),
        migrations.RemoveField(
            model_name='propertypermission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='propertypermission',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='propertypermission',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertypermission',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='propertypermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='MortgagePermission',
        ),
        migrations.DeleteModel(
            name='PropertyPermission',
        ),
    ]
