# Generated by Django 6.0.6 on 2026-08-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_complianceshare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceshare',
            name='shared_by',
        ),
    ]
