# Generated by Django 6.0.6 on 2026-08-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_remove_complianceshare_shared_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complianceandcertification',
            name='shared_with',
        ),
    ]
