# Generated by Django 6.0.6 on 2026-10-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_remove_complianceandcertification_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceandcertification',
            name='certificate_type',
            field=models.CharField(choices=[('GAS_SAFETY_CERTIFICATE', 'Gas Safety Certificate'), ('EPC_CERTIFICATE', 'Energy Performance Certificate (EPC)'), ('EICR_CERTIFICATE', 'Electrical Installation Condition Report (EICR)'), ('DEPOSIT_PROTECTION_CERTIFICATE', 'Deposit Protection Certificate'), ('RIGHT_TO_RENT_CHECK', 'Right to Rent Checks'), ('HMO_LICENCE', 'HMO Licence'), ('PROPERTY_INSURANCE_CERTIFICATE', 'Property Insurance Certificate'), ('FIRE_SAFETY_CERTIFICATE', 'Fire Safety Certificate / Fire Risk Assessment'), ('SELECTIVE_LICENCE', 'Selective Licence'), ('PAT_TESTING_CERTIFICATE', 'Portable Appliance Testing (PAT) Certificate'), ('PROPERTY_FLOOR_PLANS', 'Property Floor Plans')], default='GAS_SAFETY_CERTIFICATE', max_length=50),
        ),
    ]
