from django.urls import path

from api.views.tenants import (
    PaymentMethodListCreateView,
    PaymentMethodDetailView,
    RentPaymentListCreateView,
    RentPaymentDetailView,
    RentBalanceSummaryView,
    RentStatementView,
    DirectDebitSetupView,
    DirectDebitCompleteView,
    DirectDebitPaymentView,
    CardPaymentView,
    DirectDebitCallbackView,
    StripeWebhookView,
    GoCardlessWebhookView,
    FinancialOverviewListView,
    PropertyTenancyListView,
    PaymentHistoryView,
    MaintenanceRequestListCreateAPIView,
    MaintenanceRequestRetrieveUpdateDestroyAPIView,
    MaintenanceRequestCommentListCreateView,
    MaintenanceRequestCommentRetrieveUpdateDestroyView,
    TenantSharedComplianceListView,
    TenantListAPiView,
)

urlpatterns = [
    path(
        "/payment-methods",
        PaymentMethodListCreateView.as_view(),
        name="payment-method-list",
    ),
    path(
        "/payment-methods/<uuid:alias>",
        PaymentMethodDetailView.as_view(),
        name="payment-method-detail",
    ),
    path(
        "/rent-payments",
        RentPaymentListCreateView.as_view(),
        name="rent-payment-list",
    ),
    path(
        "/rent-payments/<uuid:alias>",
        RentPaymentDetailView.as_view(),
        name="rent-payment-detail",
    ),
    path(
        "/rent-payments/balance-summary",
        RentBalanceSummaryView.as_view(),
        name="rent-balance-summary",
    ),
    path(
        "/rent-payments/rent-statement-pdf",
        RentStatementView.as_view(),
        name="statement-full-year",
    ),
    path(
        "/payment-methods/direct-debit/setup",
        DirectDebitSetupView.as_view(),
        name="direct-debit-setup",
    ),
    path(
        "/payment-methods/direct-debit/complete",
        DirectDebitCompleteView.as_view(),
        name="direct-debit-complete",
    ),
    path(
        "/payment-methods/direct-debit/callback",
        DirectDebitCallbackView.as_view(),
        name="direct-debit-callback",
    ),
    path(
        "/rent-payments/pay-with-card", CardPaymentView.as_view(), name="pay-with-card"
    ),
    path(
        "/rent-payments/pay-with-direct-debit",
        DirectDebitPaymentView.as_view(),
        name="pay-with-direct-debit",
    ),
    path(
        "/rent-payments/payment-history",
        PaymentHistoryView.as_view(),
        name="payment-history",
    ),
    path("/stripe", StripeWebhookView.as_view(), name="webhook-stripe"),
    path("/gocardless", GoCardlessWebhookView.as_view(), name="webhook-gocardless"),
    path(
        "/property-and-tenancy-details",
        PropertyTenancyListView.as_view(),
        name="property-details",
    ),
    path(
        "/financial-overview",
        FinancialOverviewListView.as_view(),
        name="financial-overview",
    ),
    path(
        "/maintenance-requests",
        MaintenanceRequestListCreateAPIView.as_view(),
        name="maintenance-request-list-create",
    ),
    path(
        "/maintenance-requests/<uuid:alias>",
        MaintenanceRequestRetrieveUpdateDestroyAPIView.as_view(),
        name="maintenance-request-detail",
    ),
    path(
        "/maintenance-requests/<uuid:maintenance_request_alias>/comments",
        MaintenanceRequestCommentListCreateView.as_view(),
        name="maintenance-request-comments",
    ),
    path(
        "/maintenance-requests/<uuid:maintenance_request_alias>/comments/<uuid:comment_alias>",
        MaintenanceRequestCommentRetrieveUpdateDestroyView.as_view(),
        name="maintenance-request-comment-detail",
    ),
    path(
        "/compliance-certificates",
        TenantSharedComplianceListView.as_view(),
        name="tenant-shared-compliance-list",
    ),
    path("/list", TenantListAPiView.as_view(), name="tenant-list"),
]
