from django.urls import path

from api.views.tenants import (
    RentBalanceSummaryView,
    RentStatementView,
    PropertyTenancyListView,
    PaymentHistoryView,
    MaintenanceRequestListCreateAPIView,
    MaintenanceRequestRetrieveUpdateDestroyAPIView,
    MaintenanceRequestCommentListCreateView,
    MaintenanceRequestCommentRetrieveUpdateDestroyView,
    TenantSharedComplianceListView,
    TenantListAPiView,
    CardPaymentView,
    TenantStripeConnectWebhookView,
)

urlpatterns = [
    path(
        "/card-payments",
        CardPaymentView.as_view(),
        name="card-payment-create",
    ),
    path(
        "/payment-history",
        PaymentHistoryView.as_view(),
        name="payment-history",
    ),
    path(
        "/rent-payments/balance-summary",
        RentBalanceSummaryView.as_view(),
        name="rent-balance-summary",
    ),
    path(
        "/rent-payments/rent-statement-pdf",
        RentStatementView.as_view(),
        name="statement-full-year",
    ),
    path(
    "/stripe-connect-webhook",
        TenantStripeConnectWebhookView.as_view(),
        name="tenant-stripe-connect-webhook",
    ),
    path(
        "/property-and-tenancy-details",
        PropertyTenancyListView.as_view(),
        name="property-details",
    ),
    path(
        "/maintenance-requests",
        MaintenanceRequestListCreateAPIView.as_view(),
        name="maintenance-request-list-create",
    ),
    path(
        "/maintenance-requests/<uuid:alias>",
        MaintenanceRequestRetrieveUpdateDestroyAPIView.as_view(),
        name="maintenance-request-detail",
    ),
    path(
        "/maintenance-requests/<uuid:maintenance_request_alias>/comments",
        MaintenanceRequestCommentListCreateView.as_view(),
        name="maintenance-request-comments",
    ),
    path(
        "/maintenance-requests/<uuid:maintenance_request_alias>/comments/<uuid:comment_alias>",
        MaintenanceRequestCommentRetrieveUpdateDestroyView.as_view(),
        name="maintenance-request-comment-detail",
    ),
    path(
        "/compliance-certificates",
        TenantSharedComplianceListView.as_view(),
        name="tenant-shared-compliance-list",
    ),
    path("/list", TenantListAPiView.as_view(), name="tenant-list"),
]
