# Generated by Django 6.0.6 on 2026-08-25 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0004_alter_organisationuser_role'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('referral_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=16)),
                ('eligibility_deadline', models.DateTimeField(editable=False)),
                ('bank_account_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('bank_sort_code', models.CharField(blank=True, max_length=16, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ambassador Profile',
                'verbose_name_plural': 'Ambassador Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('invited_email', models.EmailField(max_length=254)),
                ('invite_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('SIGNED_UP', 'Signed Up'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('CANCELLED', 'Cancelled'), ('INVITED', 'Invited')], default='INVITED', max_length=16)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=20)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='referral.ambassadorprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('referred_organisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='organisation.organisation')),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('commission_percentage', models.PositiveSmallIntegerField(default=20)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='referral.referral')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_commissions', to='subscription.usersubscription')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Referral Commission',
                'verbose_name_plural': 'Referral Commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='referral',
            constraint=models.UniqueConstraint(fields=('ambassador', 'invited_email'), name='unique_ambassador_invited_email'),
        ),
        migrations.AddConstraint(
            model_name='referralcommission',
            constraint=models.UniqueConstraint(fields=('subscription', 'billing_period_start'), name='unique_subscription_billing_period_commission'),
        ),
    ]
