# Generated by Django 6.0.6 on 2026-08-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambassadorprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16),
        ),
    ]
