# Generated by Django 6.0.6 on 2026-08-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_alter_ambassadorprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcommission',
            name='subscription',
        ),
    ]
