# Generated by Django 6.0.6 on 2026-08-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0003_remove_referralcommission_subscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referralcommission",
            options={"ordering": ("-created_at",)},
        ),
    ]
