# Generated by Django 6.0.6 on 2026-09-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0004_alter_referralcommission_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referralcommission",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Referral Commission",
                "verbose_name_plural": "Referral Commissions",
            },
        ),
    ]
