# Generated by Django 6.0.6 on 2026-08-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral", "0003_remove_referralcommission_subscription"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["monthly_price"]},
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="allow_accountant_access",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="allow_reports",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="storage_limit_mb",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="monthly_price",
            field=models.DecimalField(decimal_places=2, null=True, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("BASIC", "Basic"),
                    ("STANDARD", "Standard"),
                    ("PREMIUM", "Premium"),
                ],
                max_length=20,
                null=True,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="referral_discount_percent",
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_properties",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="plans", to="subscription.subscriptionfeature"
            ),
        ),
        migrations.DeleteModel(
            name="UserSubscription",
        ),
    ]
