# Generated by Django 6.0.6 on 2026-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_paymenttransaction_invoice_pdf_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('TRIALING', 'Trialing'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
