# Generated by Django 6.0.6 on 2026-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='plan_name_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
