# Generated by Django 6.0.6 on 2026-09-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_paymenttransaction_plan_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscription.paymentcard'),
        ),
    ]
