# Generated by Django 6.0.6 on 2026-08-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_SUPPORT_TICKET', 'New Support Ticket'), ('NEW_TICKET_COMMENT', 'New Ticket Comment'), ('TICKET_STATUS_CHANGED', 'Ticket Status Changed'), ('NEW_MAINTENANCE_REQUEST', 'New Maintenance Request'), ('MAINTENANCE_STATUS_CHANGED', 'Maintenance Status Changed')], max_length=50),
        ),
    ]
