# Generated by Django 6.0.6 on 2026-08-11 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_notification_type'),
        ('property', '0014_property_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='property.tenant'),
        ),
    ]
