# Generated by Django 6.0.6 on 2026-10-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("NEW_SUPPORT_TICKET", "New Support Ticket"),
                    ("NEW_TICKET_COMMENT", "New Ticket Comment"),
                    ("TICKET_STATUS_CHANGED", "Ticket Status Changed"),
                    ("NEW_MAINTENANCE_REQUEST", "New Maintenance Request"),
                    ("MAINTENANCE_STATUS_CHANGED", "Maintenance Status Changed"),
                    ("NEW_MAINTENANCE_COMMENT", "New Maintenance Comment"),
                    ("CERTIFICATE_EXPIRING", "Certificate Expiring Soon"),
                ],
                max_length=50,
            ),
        ),
    ]
