# Generated by Django 6.0.6 on 2026-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationuser',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('DEACTIVATED', 'Deactivated')], default='PENDING', max_length=64, null=True, verbose_name='Status'),
        ),
    ]
