# Generated by Django 6.0.6 on 2026-07-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisationuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisationuser',
            name='status',
        ),
    ]
