# Generated by Django 6.0.6 on 2026-08-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_organisationuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationuser',
            name='role',
            field=models.CharField(blank=True, choices=[('LANDLORD', 'Landlord'), ('ADMIN', 'Admin'), ('MORTGAGE_ADVISER', 'Mortgage Adviser'), ('LETTING_AGENT', 'Letting Agent')], default='LANDLORD', max_length=64, null=True, verbose_name='Role'),
        ),
    ]
