# Generated by Django 6.0.6 on 2026-06-22 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_remove_organisationuser_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='contact_person_designation',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='is_approved',
        ),
    ]
