# Generated by Django 6.0.6 on 2026-09-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0012_merge_20260910_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
