# Generated by Django 6.0.6 on 2026-09-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0013_organisation_has_used_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='account_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
