# Generated by Django 6.0.6 on 2026-09-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0014_organisation_account_credit'),
        ('subscription', '0011_paymenttransaction_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='subscription.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='pending_plan_effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
