# Generated by Django 6.0.6 on 2026-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0015_organisationsubscription_pending_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
