# Generated by Django 6.0.6 on 2026-09-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0016_alter_organisation_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationsubscription',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
